version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
linters:
  enable:
    - copyloopvar
    - dogsled
    - dupl
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - ireturn
    - lll
    - misspell
    - nakedret
    - noctx
    - prealloc
    - revive
    - staticcheck
    - testpackage
    - unconvert
    - unparam
  settings:
    dupl:
      threshold: 100
    gocritic:
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 25
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
