linters:
  enable:
    # Code correctness and bug prevention
    - govet
    - typecheck
    - ineffassign
    - unused
    - stylecheck
    - ireturn
    - gofumpt
    - misspell
    - revive

    # Performance optimizations
    - prealloc
    - gocritic
    - noctx

    # Code complexity management
    - gocyclo
    - dupl
    - unparam
    - nakedret
    - dogsled
    - gocognit

    # Security checks
    - gosec

    # Specific checks
    - exportloopref
    - unconvert
    - gosimple
    - gochecknoinits
    - testpackage

    # Code formatting issues
    - lll

linters-settings:
  govet:
    enable:
      - shadow

  gocyclo:
    min-complexity: 25

  dupl:
    threshold: 100

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy

  lll:
    line-length: 140