version: '3'

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all

  lint:
    desc: "Run golangci-lint"
    deps: [ install:lint ]
    cmds:
      - echo "Running linters..."
      - golangci-lint run
    sources:
      - .golangci.yml
      - ./**/*.go
      - go.mod
      - go.sum

  gofumpt:
    desc: "Run gofumpt"
    deps: [ install:gofumpt ]
    cmds:
      - echo "Running gofumpt..."
      - gofumpt -e -l -w .

  test:unit:
    desc: "Run unit tests"
    cmds:
      - echo "Running unit tests..."
      - go test ./... -count=1

  test:race:
    desc: "Run unit tests under the race detector"
    cmds:
      - echo "Running unit tests with -race..."
      - go test ./... -count=1 -race

  build:
    desc: "Build the bot"
    cmds:
      - CGO_ENABLED=0 go build -o ./bin/naholosy_bot ./main

  run:
    desc: "Run service"
    deps: [ install:godotenv ]
    required:
      vars:
        - TOKEN
        - LOG_LEVEL
        - ADMIN_IDS
        - DB_PATH
    cmds:
      - godotenv -f .env go run ./main

  install:
    desc: "Install all tools"
    deps:
      - install:lint
      - install:gofumpt
      - install:godotenv

  install:lint:
    desc: "Install golangci-lint"
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
    status:
      - command -v golangci-lint

  install:gofumpt:
    desc: "Install gofumpt"
    cmds:
      - go install mvdan.cc/gofumpt@latest
    status:
      - command -v gofumpt

  install:godotenv:
    desc: "Install godotenv"
    cmds:
      - go install github.com/joho/godotenv/cmd/godotenv@latest
    status:
      - command -v godotenv
