name: CI
on:
  push: { branches: ['*'] }
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup
        with:
          go-version-file: go.mod
          check-latest: true
          task-version: '3.x'

      - name: Run linters
        run: task lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup
        with:
          go-version-file: go.mod
          check-latest: true
          task-version: '3.x'

      - name: Run unit tests
        run: task go:test:unit

  analyze:
    name: CodeQL Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go

      - name: Auto build
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3