name: CI
on:
  push: { branches: ['*'] }
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up env
        uses: ./.github/actions/setup
        with:
          go-version-file: go.mod
          check-latest: true
          task-version: '3.x'

      - name: Run linters
        run: task lint

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up env
        uses: ./.github/actions/setup
        with:
          go-version-file: go.mod
          check-latest: true
          task-version: '3.x'

      - name: Run unit tests
        run: task go:test:unit